name: Java CI with Maven

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.7
      uses: actions/setup-java@v3
      with:
        java-version: '1.7'

    - name: Build with Maven
      run: mvn -DskipTests=true --batch-mode package
      
    - uses: actions/upload-artifact@v2
      with:
        name: War-Package
        path: |
          web/target/*.war
          ws/target/*.war
